  # README: Just type make on a terminal to build the file
all: dataGenerator.c
	gcc -g -o dataGenerator dataGenerator.c

clean:
	$(RM) dataGenerator outputFile.txt memoryImage.txt inputfile.txt dataImage.txt