// Generated by BugHunter Pro Version 19.02c at 2:23:45 on 5/1/2016
// Stimulator for syncad_top

// Generation Settings:
//   Export type: Stimulus only (reactive export not enabled)
//                Delays, Samples, Markers, etc will not generate code.

// Clock Domains:


`define TB_ABORT (3'b000)
`define TB_ONCE (3'b001)
`define TB_DONE (3'b010)
`define TB_LOOPING (3'b011)
`define TB_RESTART (3'b100)
`define TB_END (3'b101)
`timescale  1 ns /  1 ps

module syncad_top;


  // Control Signal Declarations
  reg [2:0] tb_status;


  // The following initial block will start up the stimulator.
  initial
    begin
    tb_status <= `TB_ONCE;
    #55976;
    tb_status <= `TB_DONE;
    $display("Note: At %t: End of stimulus reached.  Use End Diagram Marker to extend or shorten stimulus.", $time);
    end
endmodule
